function renderFunctionToSVG(o,r,c,m){if(!o||!/[x]/.test(o))return"";o=o.replace(/²/g,"^2").replace(/π/g,"pi"),r=r||500,c=c||250;const e=40,n=r-e*2,x=c-e*2,i=-6,d=6,h=[],a=400;for(let t=0;t<=a;t++){const l=i+(d-i)*t/a;try{const f=safeMathEval(o,{x:l});isFinite(f)&&h.push({x:l,y:f})}catch{}}const p=h.filter(t=>t.y!==null).map(t=>t.y);let s,g;if(p.length>10){const t=[...p].sort((L,C)=>L-C),l=Math.floor(t.length*.02),f=Math.ceil(t.length*.98);s=t[l],g=t[f-1]}else if(p.length>0)s=Math.min(...p),g=Math.max(...p);else return"";const D=g-s||1;s-=D*.12,g+=D*.12;const y=t=>e+(t-i)/(d-i)*n,$=t=>e+(g-t)/(g-s)*x,v=m||{},R=v["--bg"]||"#0a0b0e",T=v["--border"]||"#2a3040",B=v["--accent"]||"#4f9cf9",w=v["--text2"]||"#8a97b0",M=v["--text3"]||"#4a5570",u=Math.pow(10,Math.floor(Math.log10((d-i)/5))),b=Math.pow(10,Math.floor(Math.log10((g-s)/5)));let k="";for(let t=Math.ceil(i/u)*u;t<=d;t+=u/2){const l=y(t).toFixed(1);k+=`<line x1="${l}" y1="${e}" x2="${l}" y2="${e+x}" stroke="${M}" stroke-opacity="0.3" stroke-width="0.5"/>`}for(let t=Math.ceil(s/b)*b;t<=g;t+=b/2){const l=$(t).toFixed(1);k+=`<line x1="${e}" y1="${l}" x2="${e+n}" y2="${l}" stroke="${M}" stroke-opacity="0.3" stroke-width="0.5"/>`}for(let t=Math.ceil(i/u)*u;t<=d;t+=u){const l=y(t).toFixed(1);k+=`<line x1="${l}" y1="${e}" x2="${l}" y2="${e+x}" stroke="${M}" stroke-opacity="0.6" stroke-width="1"/>`}for(let t=Math.ceil(s/b)*b;t<=g;t+=b){const l=$(t).toFixed(1);k+=`<line x1="${e}" y1="${l}" x2="${e+n}" y2="${l}" stroke="${M}" stroke-opacity="0.6" stroke-width="1"/>`}let F="";if(s<=0&&g>=0){const t=$(0).toFixed(1);F+=`<line x1="${e}" y1="${t}" x2="${e+n}" y2="${t}" stroke="${w}" stroke-width="2"/>`}if(i<=0&&d>=0){const t=y(0).toFixed(1);F+=`<line x1="${t}" y1="${e}" x2="${t}" y2="${e+x}" stroke="${w}" stroke-width="2"/>`}let E="";for(let t=Math.ceil(i/u)*u;t<=d;t+=u){if(Math.abs(t)<.001)continue;const l=y(t).toFixed(1),f=s<=0&&g>=0?$(0):e+x;E+=`<text x="${l}" y="${f+12}" fill="${w}" font-size="9" font-family="monospace" text-anchor="middle">${parseFloat(t.toPrecision(3))}</text>`}for(let t=Math.ceil(s/b)*b;t<=g;t+=b){if(Math.abs(t)<.001)continue;const l=$(t).toFixed(1),f=i<=0&&d>=0?y(0):e;E+=`<text x="${f-5}" y="${l+3}" fill="${w}" font-size="9" font-family="monospace" text-anchor="end">${parseFloat(t.toPrecision(3))}</text>`}let z="",P=!1;for(const t of h){if(t.y===null){P=!1;continue}const l=y(t.x).toFixed(2),f=$(t.y).toFixed(2);P?z+=`L${l},${f}`:(z+=`M${l},${f}`,P=!0)}return`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${r} ${c}" width="${r}" height="${c}" style="background:${R};border-radius:6px;border:1px solid ${T}">
        ${k}
        ${F}
        <path d="${z}" fill="none" stroke="${B}" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
        ${E}
    </svg>`}function getCanvasImage(o){const r=document.getElementById("chart-canvas-"+o);if(!r)return null;if(r.offsetHeight,r.width>0&&r.height>0)try{return r.toDataURL("image/png")}catch{return null}if(window._lastChartRender&&window._lastChartRender[o])try{const c=window.devicePixelRatio||1,m=r.getBoundingClientRect(),e=(m.width||r.clientWidth||300)*c,n=(m.height||r.clientHeight||150)*c;if(e>0&&n>0)return r.width=e,r.height=n,window._lastChartRender[o](r),r.toDataURL("image/png")}catch{}return null}function _downloadHTMLasPDF(o,r){const c=new Blob([o],{type:"text/html;charset=utf-8"}),m=URL.createObjectURL(c),e=document.createElement("a");e.href=m,e.download=r,document.body.appendChild(e),e.click(),document.body.removeChild(e),setTimeout(()=>URL.revokeObjectURL(m),2e3)}function exportGenPDF(){if(!LicenseManager.isPro){showProUpgradeModal("Exportar PDF","Export\xE1 tus c\xE1lculos y gr\xE1ficos en formato PDF con un solo clic.");return}showPDFChoice(o=>{if(o==="last"){let r="General",c="",m="",e=!1,n=[],x="",i="0",d=null;if(history.length>0){const a=history[0];if(x=a.expr||"",i=a.val,n=a.steps||[],r=a.module||"General",c=a.label||"",m=a.key||"",e=!a.expr&&a.module!=="general",e)d=a.chartDataUrl||getCanvasImage(r);else if((a.key==="func"||a.key==="quadratic"||a.key==="system"||a.key==="linear2var"||a.key==="eq"&&x&&/x/.test(x))&&!d&&x&&/[x]/.test(x)){const p=(ThemeManager.themes[ThemeManager.current||"dark"]||ThemeManager.themes.dark).vars;let s=x;s.includes("=")&&(s=s.split("=")[0].trim()),s=s.replace(/²/g,"^2").replace(/π/g,"pi");const g=renderFunctionToSVG(s,500,250,p);g&&(d="data:image/svg+xml,"+encodeURIComponent(g))}}if(!x&&i==="0")return;const h=e?c:x?`Resultado: ${x}`:"Resultado";exportResultPDF(r,e?m:x||"resultado",i,h,n,d)}else exportHistoryPDF()})}function showPDFChoice(o){const r=document.createElement("div");r.id="pdf-choice-overlay",r.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,0.6);z-index:9999;display:flex;align-items:center;justify-content:center;animation:fadeIn 0.2s",r.onclick=c=>{c.target===r&&r.remove()},r.innerHTML=`
        <div style="background:var(--surface2,#181c24);border:1px solid var(--border,#2a3040);border-radius:12px;padding:24px;max-width:340px;width:90%;text-align:center">
            <div style="font-size:32px;margin-bottom:8px">\u{1F4C4}</div>
            <div style="font-family:var(--sans,'Syne',sans-serif);font-size:18px;font-weight:700;color:var(--text,#e8edf5);margin-bottom:4px">Exportar PDF</div>
            <div style="font-size:12px;color:var(--text3,#4a5570);margin-bottom:20px">\xBFQu\xE9 quer\xE9s exportar?</div>
            <button id="pdf-choice-last" style="display:block;width:100%;padding:12px;margin-bottom:8px;background:var(--accent,#4f9cf9);color:#0a0b0e;border:none;border-radius:8px;font-weight:700;font-size:14px;cursor:pointer">\xDAltimo c\xE1lculo</button>
            <button id="pdf-choice-history" style="display:block;width:100%;padding:12px;margin-bottom:12px;background:var(--surface3,#1e232f);color:var(--text,#e8edf5);border:1px solid var(--border,#2a3040);border-radius:8px;font-weight:600;font-size:13px;cursor:pointer">Historial completo (${history.length} c\xE1lculos)</button>
            <button id="pdf-choice-cancel" style="background:none;border:none;color:var(--text3,#4a5570);font-size:12px;cursor:pointer;padding:4px">Cancelar</button>
        </div>`,document.body.appendChild(r),document.getElementById("pdf-choice-last").onclick=()=>{r.remove(),o("last")},document.getElementById("pdf-choice-history").onclick=()=>{r.remove(),o("history")},document.getElementById("pdf-choice-cancel").onclick=()=>{r.remove()},document.addEventListener("keydown",function c(m){m.key==="Escape"&&(r.remove(),document.removeEventListener("keydown",c))})}function exportHistoryPDF(){if(!LicenseManager.isPro){showProUpgradeModal("Exportar historial en PDF","Export\xE1 todo tu historial de c\xE1lculos en un PDF completo.");return}if(history.length===0){alert("No hay c\xE1lculos en el historial");return}const o=(ThemeManager.themes[ThemeManager.current||"dark"]||ThemeManager.themes.dark).vars,r=`*{-webkit-print-color-adjust:exact;print-color-adjust:exact;box-sizing:border-box;margin:0;padding:0}
body{background:${o["--bg"]};color:${o["--text"]};font-family:'JetBrains Mono',monospace;padding:30px;max-width:800px;margin:0 auto}
h1{font-family:'Syne',sans-serif;font-size:22px;color:${o["--accent"]};margin-bottom:5px}
.sub{font-size:11px;color:${o["--text3"]};margin-bottom:25px}
.entry{border-bottom:1px solid ${o["--border"]};padding-bottom:18px;margin-bottom:22px}
.entry:last-child{border-bottom:none;margin-bottom:0;padding-bottom:0}
.label{font-size:12px;color:${o["--text2"]};text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}
.value{font-size:28px;font-weight:700;color:${o["--text"]};margin-bottom:20px;word-break:break-all}
.step{background:${o["--surface"]};border:1px solid ${o["--border"]};border-radius:6px;padding:8px 12px;margin-bottom:4px;font-size:12px;color:${o["--text"]}}
.steps-title{font-size:12px;color:${o["--text3"]};margin-bottom:8px;margin-top:20px;text-transform:uppercase;letter-spacing:1px}
.footer{margin-top:30px;padding-top:15px;border-top:1px solid ${o["--border"]};font-size:10px;color:${o["--text3"]};text-align:center}
.badge{display:inline-block;background:${o["--accent2"]};color:${o["--bg"]};font-size:9px;padding:2px 8px;border-radius:4px;font-weight:700;margin-left:8px}`;let c="";history.forEach((n,x)=>{const i=n.key==="func"||n.key==="quadratic"||n.key==="system"||n.key==="linear2var"||n.key==="eq"&&n.expr&&/x/.test(n.expr);let d=null;if(i){let p=n.expr||(n.label?n.label.replace("f(x) = ",""):"");n.key==="eq"&&p.includes("=")&&(p=p.split("=")[0].trim()),p=p.replace(/²/g,"^2").replace(/π/g,"pi"),p&&/x/.test(p)&&(d=renderFunctionToSVG(p,500,250,o))}else n.key!=="expr"&&n.chartDataUrl&&(d=n.chartDataUrl);const h=d?d.startsWith("data:")?`<div style="margin:20px 0;text-align:center"><img src="${d}" style="max-width:100%;border-radius:8px;border:1px solid ${o["--border"]}"></div>`:`<div style="margin:20px 0;text-align:center">${d}</div>`:"";let a="";n.steps&&n.steps.length&&(a='<div class="steps-title">Pasos de resoluci\xF3n</div>',n.steps.forEach(p=>a+=`<div class="step">${p}</div>`)),c+=`<div class="entry">
            <div class="label">${n.module} \xB7 ${n.key} \xB7 ${n.time}</div>
            <div style="font-size:13px;color:${o["--text2"]};margin-bottom:4px">${n.label||""}</div>
            <div class="value">${n.val}</div>
            ${h}${a}
        </div>`});const m=`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>SumaMente - Historial</title><style>${r}</style></head><body style="background:${o["--bg"]};color:${o["--text"]};padding:30px;font-family:'JetBrains Mono',monospace">
    <h1 style="font-family:'Syne',sans-serif;font-size:22px;color:${o["--accent"]};margin-bottom:5px">SumaMente${LicenseManager.isPro?' <span class="badge">PRO</span>':""}</h1>
    <div class="sub">Historial completo \xB7 ${history.length} c\xE1lculos \xB7 ${new Date().toLocaleString("es-AR")}</div>
    ${c}
    <div class="footer">Generado por SumaMente Cientifica</div></body></html>`,e=window.open("","_blank");if(!e){alert("Permite ventanas emergentes para exportar PDF");return}e.document.write(m),e.document.close(),setTimeout(()=>{e.focus(),e.print()},500)}function exportResultPDF(o,r,c,m,e,n){if(typeof e=="string"&&e.startsWith("%"))try{e=JSON.parse(decodeURIComponent(e))}catch{e=[]}Array.isArray(e)||(e=[]);const x=new Date().toLocaleString("es-AR"),i=(ThemeManager.themes[ThemeManager.current||"dark"]||ThemeManager.themes.dark).vars,d=`*{-webkit-print-color-adjust:exact;print-color-adjust:exact;box-sizing:border-box;margin:0;padding:0}
body{background:${i["--bg"]};color:${i["--text"]};font-family:'JetBrains Mono',monospace;padding:30px;max-width:800px;margin:0 auto}
h1{font-family:'Syne',sans-serif;font-size:22px;color:${i["--accent"]};margin-bottom:5px}
.sub{font-size:11px;color:${i["--text3"]};margin-bottom:25px}
.label{font-size:12px;color:${i["--text2"]};text-transform:uppercase;letter-spacing:1px;margin-bottom:4px}
.value{font-size:28px;font-weight:700;color:${i["--text"]};margin-bottom:20px;word-break:break-all}
.step{background:${i["--surface"]};border:1px solid ${i["--border"]};border-radius:6px;padding:8px 12px;margin-bottom:4px;font-size:12px;color:${i["--text"]}}
.steps-title{font-size:12px;color:${i["--text3"]};margin-bottom:8px;margin-top:20px;text-transform:uppercase;letter-spacing:1px}
.footer{margin-top:30px;padding-top:15px;border-top:1px solid ${i["--border"]};font-size:10px;color:${i["--text3"]};text-align:center}
.badge{display:inline-block;background:${i["--accent2"]};color:${i["--bg"]};font-size:9px;padding:2px 8px;border-radius:4px;font-weight:700;margin-left:8px}`,h=n?`<div style="margin:20px 0;text-align:center"><img src="${n}" style="max-width:100%;border-radius:8px;border:1px solid ${i["--border"]}"></div>`:"";let a="";e.length&&(a='<div class="steps-title">Pasos de resoluci\xF3n</div>',e.forEach(g=>a+=`<div class="step">${g}</div>`));const p=`<!DOCTYPE html><html><head><meta charset="UTF-8"><title>SumaMente - ${m}</title><style>${d}</style></head><body style="background:${i["--bg"]};color:${i["--text"]};padding:30px;font-family:'JetBrains Mono',monospace">
    <h1 style="font-family:'Syne',sans-serif;font-size:22px;color:${i["--accent"]};margin-bottom:5px">SumaMente${LicenseManager.isPro?' <span class="badge">PRO</span>':""}</h1>
    <div class="sub">${o} \xB7 ${r} \xB7 ${x}</div>
    <div class="label">${m}</div>
    <div class="value">${c}</div>
    ${h}${a}
    <div class="footer">Generado por SumaMente Cientifica</div></body></html>`,s=window.open("","_blank");if(!s){alert("Permite ventanas emergentes para exportar PDF");return}s.document.write(p),s.document.close(),setTimeout(()=>{s.focus(),s.print()},500)}
