function toggleSearch(t){const a=document.getElementById("modal-search"),e=t===void 0?!a.classList.contains("show"):t;a.classList.toggle("show",e),e&&(document.getElementById("search-input").value="",document.getElementById("search-results").innerHTML="",document.getElementById("search-results").classList.remove("show"),renderFavorites(),setTimeout(()=>document.getElementById("search-input").focus(),100))}function selectSearchResult(t,a){toggleSearch(!1),setMode(t),setFormula(t,a);const e=document.querySelectorAll(`#mode-${t} .chip`);e.forEach(o=>o.classList.remove("active")),e.forEach(o=>{(o.getAttribute("onclick")||"").includes(`'${a}'`)&&o.classList.add("active")})}function doSearch(t){AnalyticsManager.trackSearch(t);const a=document.getElementById("search-results");if(!t.trim()){a.classList.remove("show"),a.innerHTML="";return}const e=t.toLowerCase(),o=formulaIndex.filter(s=>s.title.toLowerCase().includes(e)||s.formula.toLowerCase().includes(e)||s.modName.toLowerCase().includes(e)||s.mod.toLowerCase().includes(e)||s.key.toLowerCase().includes(e)).slice(0,30);o.length===0?a.innerHTML='<div style="padding:20px;text-align:center;color:var(--text3);font-size:13px">Sin resultados</div>':a.innerHTML=o.map(s=>{const n=isFavorite(s.mod,s.key);return`<div class="search-item" onclick="selectSearchResult('${s.mod}','${s.key}')">
                <span class="dot" style="background:${s.modColor}"></span>
                <span class="si-mod">${s.modName}</span>
                <span class="si-name">${s.title}</span>
                <button class="si-star${n?" active":""}" onclick="event.stopPropagation();toggleFav('${s.mod}','${s.key}','${s.title.replace(/'/g,"\\'")}')">${n?"\u2605":"\u2606"}</button>
            </div>`}).join(""),a.classList.add("show")}function getFavorites(){try{return JSON.parse(localStorage.getItem("SumaMente_favorites"))||[]}catch{return[]}}function isFavorite(t,a){return getFavorites().some(e=>e.mod===t&&e.key===a)}function toggleFav(t,a,e){let o=getFavorites();const s=o.findIndex(c=>c.mod===t&&c.key===a);if(s>=0)o.splice(s,1);else{if(!LicenseManager.isPro&&o.length>=3){showProUpgradeModal("M\xE1s favoritos","Pod\xE9s tener hasta 3 f\xF3rmulas favoritas. Actualiz\xE1 a PRO para favoritos ilimitados.");return}o.push({mod:t,key:a,title:e||a})}try{localStorage.setItem("SumaMente_favorites",JSON.stringify(o))}catch{}const n=document.getElementById("search-input");n&&doSearch(n.value),renderFavorites(),updateChipStars()}function renderFavorites(){const t=document.getElementById("search-favorites"),a=getFavorites();if(a.length===0){t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div><div class="fav-empty">Sin favoritos a\xFAn. Hac\xE9 clic en la estrella \u2B50 de una f\xF3rmula para agregarla.</div>';return}t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div>'+a.map(e=>{const o=MODE_COLORS[e.mod]||"#4f9cf9",s=e.title||(FORMS[e.mod]&&FORMS[e.mod][e.key]?FORMS[e.mod][e.key].title:e.key);return`<div class="search-item" onclick="selectSearchResult('${e.mod}','${e.key}')">
            <span class="dot" style="background:${o}"></span>
            <span class="si-mod">${MODE_NAMES[e.mod]||e.mod}</span>
            <span class="si-name">${s}</span>
            <button class="si-star active" onclick="event.stopPropagation();toggleFav('${e.mod}','${e.key}','${(s||"").replace(/'/g,"\\'")}')">\u2605</button>
        </div>`}).join("")}function enhanceChips(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const a=t.getAttribute("onclick");if(!a)return;const e=a.match(/setFormula\(\s*'(\w+)'\s*,\s*'(\w+)'/);if(!e)return;const o=e[1],s=e[2];t.dataset.mod=o,t.dataset.key=s;const n=document.createElement("span");n.className="chip-star",n.textContent="\u2606",n.onclick=c=>{c.stopPropagation(),c.preventDefault();const i=FORMS[o]&&FORMS[o][s];toggleFav(o,s,i?i.title:s)},t.prepend(n),t.style.paddingLeft="6px"}),updateChipStars()}function updateChipStars(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const a=t.querySelector(".chip-star");if(!a)return;const e=isFavorite(t.dataset.mod,t.dataset.key);a.textContent=e?"\u2605":"\u2606",a.classList.toggle("active",e)})}
