function toggleSearch(t){const s=document.getElementById("modal-search"),e=t===void 0?!s.classList.contains("show"):t;s.classList.toggle("show",e),e&&(document.getElementById("search-input").value="",document.getElementById("search-results").innerHTML="",document.getElementById("search-results").classList.remove("show"),renderFavorites(),setTimeout(()=>document.getElementById("search-input").focus(),100))}function selectSearchResult(t,s){toggleSearch(!1),setMode(t),setFormula(t,s);const e=document.querySelectorAll(`#mode-${t} .chip`);e.forEach(a=>a.classList.remove("active")),e.forEach(a=>{(a.getAttribute("onclick")||"").includes(`'${s}'`)&&a.classList.add("active")})}function doSearch(t){AnalyticsManager.trackSearch(t);const s=document.getElementById("search-results");if(!t.trim()){s.classList.remove("show"),s.innerHTML="";return}const e=t.toLowerCase(),a=formulaIndex.filter(o=>o.title.toLowerCase().includes(e)||o.formula.toLowerCase().includes(e)||o.modName.toLowerCase().includes(e)||o.mod.toLowerCase().includes(e)||o.key.toLowerCase().includes(e)).slice(0,30);a.length===0?s.innerHTML='<div style="padding:20px;text-align:center;color:var(--text3);font-size:13px">Sin resultados</div>':s.innerHTML=a.map(o=>{const n=isFavorite(o.mod,o.key);return`<div class="search-item" onclick="selectSearchResult('${o.mod}','${o.key}')">
                <span class="dot" style="background:${o.modColor}"></span>
                <span class="si-mod">${o.modName}</span>
                <span class="si-name">${o.title}</span>
                <button class="si-star${n?" active":""}" onclick="event.stopPropagation();toggleFav('${o.mod}','${o.key}','${o.title.replace(/'/g,"\\'")}')">${n?"\u2605":"\u2606"}</button>
            </div>`}).join(""),s.classList.add("show")}function getFavorites(){try{return JSON.parse(localStorage.getItem("SumaMente_favorites"))||[]}catch{return[]}}function isFavorite(t,s){return getFavorites().some(e=>e.mod===t&&e.key===s)}function toggleFav(t,s,e){let a=getFavorites();const o=a.findIndex(c=>c.mod===t&&c.key===s);if(o>=0)a.splice(o,1);else{if(!LicenseManager.isPro&&a.length>=3){showProUpgradeModal("M\xE1s favoritos","Pod\xE9s tener hasta 3 f\xF3rmulas favoritas. Actualiz\xE1 a PRO para favoritos ilimitados.");return}a.push({mod:t,key:s,title:e||s})}try{localStorage.setItem("SumaMente_favorites",JSON.stringify(a))}catch{}const n=document.getElementById("search-input");n&&doSearch(n.value),renderFavorites(),updateChipStars()}function renderFavorites(){const t=document.getElementById("search-favorites"),s=getFavorites();if(s.length===0){t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div><div class="fav-empty">Sin favoritos a\xFAn. Hac\xE9 clic en la estrella \u2B50 de una f\xF3rmula para agregarla.</div>';return}t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div>'+s.map(e=>{const a=MODE_COLORS[e.mod]||"#4f9cf9",o=e.title||(FORMS[e.mod]&&FORMS[e.mod][e.key]?FORMS[e.mod][e.key].title:e.key);return`<div class="search-item" onclick="selectSearchResult('${e.mod}','${e.key}')">
            <span class="dot" style="background:${a}"></span>
            <span class="si-mod">${MODE_NAMES[e.mod]||e.mod}</span>
            <span class="si-name">${o}</span>
            <button class="si-star active" onclick="event.stopPropagation();toggleFav('${e.mod}','${e.key}','${(o||"").replace(/'/g,"\\'")}')">\u2605</button>
        </div>`}).join("")}function enhanceChips(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const s=t.getAttribute("onclick");if(!s)return;const e=s.match(/setFormula\(\s*'(\w+)'\s*,\s*'(\w+)'/);if(!e)return;const a=e[1],o=e[2];t.dataset.mod=a,t.dataset.key=o;const n=document.createElement("span");n.className="chip-star",n.textContent="\u2606",n.onclick=c=>{c.stopPropagation(),c.preventDefault();const i=FORMS[a]&&FORMS[a][o];toggleFav(a,o,i?i.title:o)},t.prepend(n),t.style.paddingLeft="6px"}),updateChipStars()}function updateChipStars(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const s=t.querySelector(".chip-star");if(!s)return;const e=isFavorite(t.dataset.mod,t.dataset.key);s.textContent=e?"\u2605":"\u2606",s.classList.toggle("active",e)})}
