function toggleSearch(t){const s=document.getElementById("modal-search"),e=t===void 0?!s.classList.contains("show"):t;s.classList.toggle("show",e),e&&(document.getElementById("search-input").value="",document.getElementById("search-results").innerHTML="",document.getElementById("search-results").classList.remove("show"),renderFavorites(),setTimeout(()=>document.getElementById("search-input").focus(),100))}function selectSearchResult(t,s){toggleSearch(!1),setMode(t),setFormula(t,s);const e=document.querySelectorAll(`#mode-${t} .chip`);e.forEach(n=>n.classList.remove("active")),e.forEach(n=>{(n.getAttribute("onclick")||"").includes(`'${s}'`)&&n.classList.add("active")})}function doSearch(t){AnalyticsManager.trackSearch(t);const s=document.getElementById("search-results");if(!t.trim()){s.classList.remove("show"),s.innerHTML="";return}const e=t.toLowerCase(),n=formulaIndex.filter(a=>a.title.toLowerCase().includes(e)||a.formula.toLowerCase().includes(e)||a.modName.toLowerCase().includes(e)||a.mod.toLowerCase().includes(e)||a.key.toLowerCase().includes(e)).slice(0,30);n.length===0?s.innerHTML='<div style="padding:20px;text-align:center;color:var(--text3);font-size:13px">Sin resultados</div>':s.innerHTML=n.map(a=>{const o=isFavorite(a.mod,a.key);return`<div class="search-item" onclick="selectSearchResult('${a.mod}','${a.key}')">
                <span class="dot" style="background:${a.modColor}"></span>
                <span class="si-mod">${a.modName}</span>
                <span class="si-name">${a.title}</span>
                <button class="si-star${o?" active":""}" onclick="event.stopPropagation();toggleFav('${a.mod}','${a.key}','${a.title.replace(/'/g,"\\'")}')">${o?"\u2605":"\u2606"}</button>
            </div>`}).join(""),s.classList.add("show")}function getFavorites(){try{return JSON.parse(localStorage.getItem("SumaMente_favorites"))||[]}catch{return[]}}function isFavorite(t,s){return getFavorites().some(e=>e.mod===t&&e.key===s)}function toggleFav(t,s,e){let n=getFavorites();const a=n.findIndex(c=>c.mod===t&&c.key===s);if(a>=0)n.splice(a,1);else{if(!LicenseManager.isPro&&n.length>=3){showProUpgradeModal("M\xE1s favoritos","Pod\xE9s tener hasta 3 f\xF3rmulas favoritas. Actualiz\xE1 a PRO para favoritos ilimitados.");return}n.push({mod:t,key:s,title:e||s})}try{localStorage.setItem("SumaMente_favorites",JSON.stringify(n))}catch{}const o=document.getElementById("search-input");o&&doSearch(o.value),renderFavorites(),updateChipStars()}function renderFavorites(){const t=document.getElementById("search-favorites"),s=getFavorites();if(s.length===0){t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div><div class="fav-empty">Sin favoritos a\xFAn. Hac\xE9 clic en la estrella \u2B50 de una f\xF3rmula para agregarla.</div>';return}t.innerHTML='<div class="fav-title">\u2B50 Favoritos</div>'+s.map(e=>{const n=MODE_COLORS[e.mod]||"#4f9cf9",a=e.title||(FORMS[e.mod]&&FORMS[e.mod][e.key]?FORMS[e.mod][e.key].title:e.key);return`<div class="search-item" onclick="selectSearchResult('${e.mod}','${e.key}')">
            <span class="dot" style="background:${n}"></span>
            <span class="si-mod">${MODE_NAMES[e.mod]||e.mod}</span>
            <span class="si-name">${a}</span>
            <button class="si-star active" onclick="event.stopPropagation();toggleFav('${e.mod}','${e.key}','${(a||"").replace(/'/g,"\\'")}')">\u2605</button>
        </div>`}).join("")}function enhanceChips(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const s=t.getAttribute("onclick");if(!s)return;const e=s.match(/setFormula\(\s*'(\w+)'\s*,\s*'(\w+)'/);if(!e)return;const n=e[1],a=e[2];t.dataset.mod=n,t.dataset.key=a;const o=document.createElement("span");o.className="chip-star",o.textContent="\u2606",o.onclick=c=>{c.stopPropagation(),c.preventDefault();const i=FORMS[n]&&FORMS[n][a];toggleFav(n,a,i?i.title:a)},t.prepend(o),t.style.paddingLeft="6px"}),updateChipStars()}function updateChipStars(){document.querySelectorAll(".formula-chips .chip").forEach(t=>{const s=t.querySelector(".chip-star");if(!s)return;const e=isFavorite(t.dataset.mod,t.dataset.key);s.textContent=e?"\u2605":"\u2606",s.classList.toggle("active",e)})}
